#cgvsimulation:cgvsimulation.o main.o
#	g++ cgvsimulation.o main.o -o cgvsimulation
#cgvsimulation.o:cgvsimulation.cpp
#	g++ -c cgvsimulation.cpp
#main.o:main.cpp
# 	g++ -c main.cpp
mvsc:*.cpp
	g++ main.cpp cgvsimulation.cpp -o mvsc
clean:
	rm mvsc
